apiVersion: v1
kind: Service
metadata:
  name: profile-app
spec:
  type: {{ .Values.service.type }}
  selector:
    app: profile-app
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 3000
      nodePort: {{ .Values.service.nodePort }}
